// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbIjlxUHSWRK1mJpqUAQPCIdZan0H41Hc',
    appId: '1:655355115956:web:0f133c8b70349e995b9ae1',
    messagingSenderId: '655355115956',
    projectId: 'travel-plan-4a24b',
    authDomain: 'travel-plan-4a24b.firebaseapp.com',
    storageBucket: 'travel-plan-4a24b.appspot.com',
    measurementId: 'G-NYT8EGN1H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBbOMijHe4zXYMXHVl4Pf8Bmf6197of4o',
    appId: '1:281868381414:android:f5577e28ce622149081f27',
    messagingSenderId: '655355115956',
    projectId: 'travelplanning-64738',
    storageBucket: 'travel-plan-4a24b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-dE0Ij85BO26yefZ-0CnHeTwtMXsvVVE',
    appId: '1:655355115956:ios:9a9c405d246efb495b9ae1',
    messagingSenderId: '655355115956',
    projectId: 'travel-plan-4a24b',
    storageBucket: 'travel-plan-4a24b.appspot.com',
    iosClientId: '655355115956-bpej0mconju34vqndotlnep1dmv86unu.apps.googleusercontent.com',
    iosBundleId: 'com.example.booking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-dE0Ij85BO26yefZ-0CnHeTwtMXsvVVE',
    appId: '1:655355115956:ios:9a9c405d246efb495b9ae1',
    messagingSenderId: '655355115956',
    projectId: 'travel-plan-4a24b',
    storageBucket: 'travel-plan-4a24b.appspot.com',
    iosClientId: '655355115956-bpej0mconju34vqndotlnep1dmv86unu.apps.googleusercontent.com',
    iosBundleId: 'com.example.booking',
  );
}
